# Generated by Django 4.2.7 on 2023-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Creation_date", models.DateTimeField(auto_now_add=True)),
                ("First_name", models.CharField(max_length=100)),
                ("Last_name", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=150)),
                ("Phone", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=300)),
                ("Company", models.CharField(max_length=255)),
            ],
        ),
    ]
